name: Code Quality Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # Ensure it matches your project version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install Flake8
          pip install -r requirements.txt  # Ensure all dependencies are installed

      - name: Run Flake8
        run: flake8 . --count --show-source --statistics
